apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ibonjour-ceaee-certificate
  namespace: ibonjour-ceaee
spec:
  secretName: ibonjour-ceaee-secret-tls
  commonName: thanak81-ibonjour.assessify.org
  dnsNames:
  - thanak81-ibonjour.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
